package com.jachs.hibernate.entity;

import org.hibernate.annotations.Entity;
import org.springframework.data.annotation.Id;

// Generated 2018-11-7 14:40:15 by Hibernate Tools 4.0.1.Final

/**
 * Tb2 generated by hbm2java
 */
public class Tb2 implements java.io.Serializable {
	private String aa;
	private String bb;
	private String cc;

	public Tb2() {
	}

	public Tb2(String aa) {
		this.aa = aa;
	}

	public Tb2(String aa, String bb, String cc) {
		this.aa = aa;
		this.bb = bb;
		this.cc = cc;
	}

	public String getAa() {
		return this.aa;
	}

	public void setAa(String aa) {
		this.aa = aa;
	}

	public String getBb() {
		return this.bb;
	}

	public void setBb(String bb) {
		this.bb = bb;
	}

	public String getCc() {
		return this.cc;
	}

	public void setCc(String cc) {
		this.cc = cc;
	}

}
