package com.jachs.hibernate.entity;
// Generated 2018-11-7 14:40:15 by Hibernate Tools 4.0.1.Final

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private String name;
	private Integer age;
	private String gender;

	public Test() {
	}

	public Test(String name) {
		this.name = name;
	}

	public Test(String name, Integer age, String gender) {
		this.name = name;
		this.age = age;
		this.gender = gender;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

}
