DROP TABLE example;
CREATE TABLE example ( id int NOT NULL AUTO_INCREMENT, score int, my_student_id int, my_subject_id int, PRIMARY KEY (id), INDEX FKb2ismihrx3ymsmg10vpoxgcf3 (my_student_id), INDEX FK7v2s906q8jpgxpscvjnnoe9jk (my_subject_id) ) ENGINE=InnoDB DEFAULT CHARSET=gbk;
insert into example (id, score, my_student_id, my_subject_id) values (1, 95, 1, 1);
DROP TABLE my_class;
CREATE TABLE my_class ( class_id int NOT NULL AUTO_INCREMENT, class_name varchar(20), class_type int, PRIMARY KEY (class_id) ) ENGINE=InnoDB DEFAULT CHARSET=gbk;
insert into my_class (class_id, class_name, class_type) values (1, '小学一年级', 10);
insert into my_class (class_id, class_name, class_type) values (2, '二年级', 2);
DROP TABLE my_student;
CREATE TABLE my_student ( student_id int NOT NULL AUTO_INCREMENT, student_age int, student_gender int, student_name varchar(5), classid int, PRIMARY KEY (student_id), INDEX FKsyie223jogm0ctp8n60sad5hb (classid) ) ENGINE=InnoDB DEFAULT CHARSET=gbk;
insert into my_student (student_id, student_age, student_gender, student_name, classid) values (1, 2, 0, '张2岁', 2);
insert into my_student (student_id, student_age, student_gender, student_name, classid) values (2, 3, 0, '张3岁', 2);
DROP TABLE my_subject;
CREATE TABLE my_subject ( subject_id int NOT NULL AUTO_INCREMENT, subject_name varchar(5), PRIMARY KEY (subject_id) ) ENGINE=InnoDB DEFAULT CHARSET=gbk;
insert into my_subject (subject_id, subject_name) values (1, '语文');
DROP TABLE my_subject_my_student_list;
CREATE TABLE my_subject_my_student_list ( my_subject_subject_id int NOT NULL, my_student_list_student_id int NOT NULL, INDEX FKhx7pmxx83i6d5d76arwv11vn6 (my_student_list_student_id), INDEX FK39kin83jdllamsxhee72lnu94 (my_subject_subject_id) ) ENGINE=InnoDB DEFAULT CHARSET=gbk;
insert into my_subject_my_student_list (my_subject_subject_id, my_student_list_student_id) values (1, 1);
insert into my_subject_my_student_list (my_subject_subject_id, my_student_list_student_id) values (1, 2);
ALTER TABLE example ADD CONSTRAINT FK7v2s906q8jpgxpscvjnnoe9jk FOREIGN KEY (my_subject_id) REFERENCES my_subject (subject_id) ;
ALTER TABLE example ADD CONSTRAINT FKb2ismihrx3ymsmg10vpoxgcf3 FOREIGN KEY (my_student_id) REFERENCES my_student (student_id);
ALTER TABLE my_student ADD CONSTRAINT FKsyie223jogm0ctp8n60sad5hb FOREIGN KEY (classid) REFERENCES my_class (class_id);
ALTER TABLE my_subject_my_student_list ADD CONSTRAINT FK39kin83jdllamsxhee72lnu94 FOREIGN KEY (my_subject_subject_id) REFERENCES my_subject (subject_id) ;
ALTER TABLE my_subject_my_student_list ADD CONSTRAINT FKhx7pmxx83i6d5d76arwv11vn6 FOREIGN KEY (my_student_list_student_id) REFERENCES my_student (student_id);
