spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password:
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间(毫秒)
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: stat, wall, log4j
    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#druid访问地址http://localhost:8080/druid/login.html    
###通过下面的配置启用所有的监控端点，默认情况下，这些端点是禁用的；加入这个配置。监控所有接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
#通过actuator/+端点名就可以获取相应的信息。
#/actuator/beans 显示应用程序中所有Spring bean的完整列表。
#/actuator/configprops 显示所有配置信息。
#/actuator/env 陈列所有的环境变量。
#/actuator/mappings 显示所有@RequestMapping的url整理列表。
#/actuator/health 显示应用程序运行状况信息 up表示成功 down失败
#/actuator/info 查看自定义应用信息